
language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer install --dev

script: mvn install:install-file "-Dfile=Cobra.jar" "-DgroupId=com.Cobra" "-DartifactId=Cobra" "-Dversion=0.98.4" "-Dpackaging=jar" "-DgeneratePom=true"

notifications:
    email:
        - example.mail@example.com

    